# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from public_var import antrian
from pathlib import Path
from tkinter import Tk, Canvas, PhotoImage, font
import time
from datetime import datetime

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/kevinadhaikal/struktur_data/project/assets/frame0")

jam_canvas = None
date_canvas = None
canvas = None

# Mapping manual hari dan bulan
nama_hari = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu']
nama_bulan = [
    '', 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
    'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
]

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def thread_time():
    date_now = None
    while 1:
        date_now = datetime.now()
        
        try:
            tanggal_now = f"{nama_hari[date_now.weekday()]}, {date_now.day} {nama_bulan[date_now.month]} {date_now.year}"
        except ValueError:
            tanggal_now = date_now.strftime('%A, %#d %B %Y')

        my_font = font.Font(family="Inter", size=-24, weight="bold")
        text_width = my_font.measure(tanggal_now)
        x_max = 789 - text_width
        
        jam_now = date_now.strftime("%H:%M:%S")
        jam_font = font.Font(family="Inter", size=-24, weight="bold")
        jam_width = jam_font.measure(jam_now)
        center_x = x_max + (text_width / 2)
        jam_x = center_x - (jam_width / 2)

        canvas.after(0, lambda: antrian["display_canvas"].itemconfig(date_canvas, text=tanggal_now))
        canvas.after(0, lambda: antrian["display_canvas"].itemconfig(jam_canvas, text=jam_now))
        canvas.coords(date_canvas, x_max, 32.0)
        canvas.coords(jam_canvas, jam_x, 64.0)

        time.sleep(1)

def init():
    antrian["display_window"] = Tk()

    antrian["display_window"].geometry("800x600")
    antrian["display_window"].configure(bg = "#FFFFFF")

    antrian["display_canvas"] = Canvas(
        antrian["display_window"],
        bg = "#FFFFFF",
        height = 600,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    global canvas
    canvas = antrian["display_canvas"]

    canvas.place(x = 0, y = 0)
    canvas.create_image(
        404.0,
        300.0,
        image=PhotoImage(file=relative_to_assets("image_1.png"))
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    canvas.create_image(
        200,
        300.65932471489737,
        image=image_image_2
    )

    canvas.create_text(
        111.0,
        67.0,
        anchor="nw",
        text="RUMAH SAKIT SEJAHTERA",
        fill="#212121",
        font=("Inter", 28 * -1)
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    canvas.create_image(
        646.0,
        130,
        image=image_image_3
    )

    canvas.create_rectangle(
        31.0,
        182.0,
        261.0,
        349.0,
        fill="#D9D9D9",
        outline="")

    antrian["cao_label"] = canvas.create_text(
        (31 + 261) / 2,
        (182 + 349) / 2,
        anchor="center",
        text="Kosong",
        fill="#000000",
        font=("Inter Medium", 30 * -1)
    )

    canvas.create_rectangle(
        540.0,
        182.0,
        770.0,
        349.0,
        fill="#D9D9D9",
        outline="")

    antrian["cap_label"] = canvas.create_text(
        (540 + 770) / 2,
        (182 + 349) / 2,
        anchor="center",
        text="Kosong",
        fill="#000000",
        font=("Inter Medium", 30 * -1)
    )

    canvas.create_text(
        84.0,
        146.0,
        anchor="nw",
        text="Antrian Obat",
        fill="#424242",
        font=("Inter SemiBold", 20 * -1)
    )

    canvas.create_rectangle(
        540.0,
        405.0,
        770.0,
        572.0,
        fill="#D9D9D9",
        outline="")

    antrian["nap_label"] = canvas.create_text(
        (540 + 770) / 2,
        (405 + 572) / 2,
        anchor="center",
        text="Kosong",
        fill="#000000",
        font=("Inter Medium", 30 * -1)
    )

    canvas.create_text(
        556.0,
        372.0,
        anchor="nw",
        text="Antrian Pembayaran",
        fill="#424242",
        font=("Inter SemiBold", 20 * -1)
    )

    canvas.create_rectangle(
        31.0,
        405.0,
        261.0,
        572.0,
        fill="#D9D9D9",
        outline="")

    antrian["nao_label"] = canvas.create_text(
        (31 + 261) / 2,
        (405 + 572) / 2,
        anchor="center",
        text="Kosong",
        fill="#000000",
        font=("Inter Medium", 30 * -1)
    )

    canvas.create_text(
        84.0,
        372.0,
        anchor="nw",
        text="Antrian Obat",
        fill="#424242",
        font=("Inter SemiBold", 20 * -1)
    )

    canvas.create_text(
        309.0,
        372.0,
        anchor="nw",
        text="Antrian Selanjutnya",
        fill="#424242",
        font=("Inter SemiBold", 20 * -1)
    )

    canvas.create_text(
        316.0,
        146.0,
        anchor="nw",
        text="Antrian Sekarang",
        fill="#424242",
        font=("Inter SemiBold", 20 * -1)
    )

    canvas.create_text(
        557.0,
        146.0,
        anchor="nw",
        text="Antrian Pembayaran",
        fill="#424242",
        font=("Inter SemiBold", 20 * -1)
    )


    canvas.create_rectangle(
        16.999971986377204,
        360.0,
        789.0,
        362.00000015251675,
        fill="#000000",
        outline="")

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    canvas.create_image(
        60,
        65,
        image=image_image_4
    )

    text_value = "1 Mei 2025"
    my_font = font.Font(family="Inter", size=-24, weight="bold")
    text_width = my_font.measure(text_value)
    x_max = 789 - text_width

    global date_canvas
    date_canvas = canvas.create_text(
        x_max,
        32.0,
        anchor="nw",
        text=text_value,
        fill="#212121",
        font=my_font
    )

    jam_font = font.Font(family="Inter", size=-24, weight="bold")
    jam_width = jam_font.measure("00:00:00")
    center_x = x_max + (text_width / 2)
    jam_x = center_x - (jam_width / 2)

    global jam_canvas
    jam_canvas = canvas.create_text(
        jam_x,
        64,
        anchor="nw",
        text="12:12:12",
        fill="#212121",
        font=jam_font
    )

    canvas.create_rectangle(
        17.0,
        125.0,
        789.0,
        126.0,
        fill="#000000",
        outline="")

    canvas.create_text(
        166.0,
        30.0,
        anchor="nw",
        text="NOMOR ANTRIAN",
        fill="#212121",
        font=("Inter Bold", 28 * -1)
    )

    antrian["display_window"].protocol("WM_DELETE_WINDOW", lambda: None)
    antrian["display_window"].resizable(False, False)
    antrian["display_ready"].signal()
    antrian["display_window"].mainloop()